### PR TITLE
Improved TextMate grammar for glaemscribe and created a Vscode extension

### PR DESCRIPTION
**Pull request by laicasaane**
I've improved TextMate grammar for .glaem and .cst. I've tried to cover every structure in the document and existing modes. If something is missing, just let me know.

The improved grammars are written in yaml (regex strings can be read much more easier) and output to json format, with the support of this extension: https://github.com/Togusa09/vscode-tmlanguage/

### CODE REVIEW

**Comment by laicasaane** [comment]
This is how it works in One Dark Pro theme

image

image

image

image

image

**Comment by BenTalagan** [comment]
Hi Laicasaane, this looks awesome. Thanks a lot for your contribution! I let you polish your PR before merging ; I haven't manage to install it in VS Code (I'm not familiar with it, I'm used to Textmate), is there an easy way to install it (documentation on the net references vsix files for local extensions)? Also, it could be nice to port back your changes to the original Textmate bundle.

**Comment by laicasaane** [comment]
>  is there an easy way to install it

Are you asking about vscode installation or the extension? Either way, they are both quite easy to install. For vscode, just follow the document here: https://code.visualstudio.com/docs/setup/setup-overview

To install any local extension, just drop the its folder (e.g. 'glaemscribe-1.0.0') into the extension directory of vscode:

- **Windows** %USERPROFILE%\.vscode\extensions
- **Mac** $HOME/.vscode/extensions
- **Linux** $HOME/.vscode/extensions

Another way to install extensions is via the Extensions Gallery. I think after finish the grammar file, I should publish it on the Gallery so anyone can install it efficiently without cloning the repo.

**Comment by BenTalagan** [comment]
`To install any local extension, just drop the its folder (e.g. 'glaemscribe-1.0.0') into the extensions directory of vscode`

Ok! This was the part I was missing. I thought an extension could only be installed from a bundled extension (.vsix) and was not aware you could copy paste it in the extensions directory.

**Comment by laicasaane** [comment]
Just drop the extension folder into that directory and restart vscode ;) Pretty easy.

> I thought an extension could only be installed from a bundled extension (.vsix)

Me too! Before I made this extension 😆

**Comment by BenTalagan** [comment]
Thanks for all these precisions. This works well! And it is far more complete than the quick bundle I had made for TextMate. Tell me when you're finished, so that I can make a review ; I'll try to backport your changes for TextMate too.

**Comment by BenTalagan** [comment]
Ok, I've found a way to backport your work to TextMate. The files need to be in the plist format, and it can be done with `plutil` under MacOS : 

`plutil -convert xml1 cst.tmLanguage.json -o cst.tmLanguage`
`plutil -convert xml1 glaem.tmLanguage.json -o glaem.tmLanguage`

will give the correct plist files for the TextMate bundle (they just have to be put in the `Languages` directory of the bundle.

**Comment by laicasaane** [comment]
Great,, I've finished it all! Well, it's too late now and I'm sure that there are something I didn't take care of. So, please review it and tell me if I've missed any.

Oh, and there is 1 case that I don't quite understand. Please look into the `japanese-tengwar.glaem`, line 280.

Is the right sheaf an equivalence sequence?
image

If it is, the commas should be highlighted as normal equivalence sequences.
image

**Comment by laicasaane** [comment]
Just another thing. {NULL} and {NBSP} and the likes should be constants or keywords. But I'm treating them as variable for now.

image

I will need a complete list of them to work on. Or do you have any other idea?

**Comment by BenTalagan** [comment]
> Well, it's too late now

Wow, are you on the Viêt Nam Time zone ? Sure it's pretty late :D

> Oh, and there is 1 case that I don't quite understand. Please look into the japanese-tengwar.glaem, line 280.
> Is the right sheaf an equivalence sequence?

It is not : it's a special feature I've added when developing the japanese mode, the right member of the assignation is in fact a cross rule schema. The main macro for japanese is quite complex and depending on parameters, some inversion may or may not happen. Thus, the cross rule schema is in fact a variable which may change depending on these parameters to allow (or not) the inversion :)

I have one comment though for the moment, before reviewing everything, I think it could be nice to have a generic grammar for glaeml (not .glaem, not .cst, but generic glaeml files). That was my purpose at first for this TextMate bundle, but your work is way beyond that since you've covered the complete mode and charset files. Generic glaeml is actually a lot simpler since you don't need to know anything about the content, just the structure (comments, elements, attributes, text, etc).

**Comment by BenTalagan** [comment]
> I will need a complete list of them to work on. Or do you have any other idea?

ATM the list can be found in the source code [here](https://github.com/BenTalagan/glaemscribe/blob/3c25e24cd5eb7b4ab1aed230021e972f39f36bcf/lib_js/api/rule_group.js#L321-L337). 

Basically, these are redefinitions of the special characters used in the rule syntax : ()[]{}* etc, plus the special "spaces" like NBSP, ZWJ etc.

**Comment by laicasaane** [comment]
Ah yes, at the start, I've just thought of changing your tmlanguage file a bit. But after changing here and there, I eventually decided to rework it completely. And well, since I'm having much free time these days, I just need something to do, to kill time the possitive way. 😂

Well, please take time review it for now. For me, I should go to rest. 😃

**Comment by BenTalagan** [comment]
Yes, I won't comment anymore until tomorrow because I feel it will prevent you from going to sleep :D By the way, thank you very much for this contribution, this is awesome work, and very useful!

**Comment by BenTalagan** [comment]
I have a remark concerning tokens : output tokens are colorized everywhere (output tokens are made of uppercase letters with underscores, like PARMA, SILME_NUQUERNA, etc). But they can only happen in the right member of a rule. Uppercase characters are legit in the left member of a rule but they don't represent tokens, they are just input uppercase characters (it never happens in my modes since the whole input text is converted to lowercase by the preprocessor `\downcase` operator). In the japanese mode for example the numerals A and B are colorized. Also the rule r_ --> ORE colorizes the underscore after r and it probably should not.

**Comment by laicasaane** [comment]
That' right, I know that too but still need your help to confirm where the tokens are valid, anh what is the rule of a token to separate it from the input characters.

**Comment by BenTalagan** [comment]
Hmm, the logic should be to recognize what's left and what's right of `-->`. 

On the left and right part can be : 

- equivalences, sheaves
- variables

On the left side : 

- input chars (anything which is not recognized as equivalences/sheaves/vars structure).

On the right side : 

- output tokens

Do you think it's possible to treat things differently on the left and right side of a rule ?

**Comment by laicasaane** [comment]
> Hmm, the logic should be to recognize what's left and what's right of `-->`.

Yeah. Last night I had refined the grammar to recognize left and right sheaves of `-->`, and `===`/`<=>` separatedly. In the start I just wrote a very being generic grammar. But last night I figure out a more refined way to do it. (Mainly fighting with regex!)

**Comment by laicasaane** [comment]
Another problem might be terminology. I've read the document many time but it seems I couldn't get the exact term for each part of glaem. And till now I used to think the entire left and right of `-->` are "sheaf", and a "sheaf" could contain linkable chains, equivalence sequences,... So I might need your help in this subject too. 🤔

**Comment by BenTalagan** [comment]
Ok, let's try to explain it and tell me if it's not clear :-) The problem is probably that for convenience, the syntax of the left part of a rule is lazy and thus you can "omit" some parts, example :  

`[(a)]`

is

- a **sheaf chain** of size **1 sheaf**
- the **sheaf** is of size **1 fragment**
- the **fragment** is a sequence of equivalences of size **1 equivalence**
- the **equivalence** has only **1 atomic sequence**
- the **atomic sequence** has only **1 char**

Pheeew! But you can also write it `[a]`, `(a)`, or `a`.

So the order of inclusion in the engine is the following : 

- 1 SheafChain < [1..N] Sheaves enclosed by `[...]` (or not if of size 1)`
- 1 Sheaf < [1..N] Fragments (separed by `*` inside the sheaf, or no separator if of size 1 fragment)`
- 1 Fragment < [1..N] Equivalences enclosed by `(...)` (or not if of size 1)`
- 1 equivalence < [1..N] Atomic sequences (separed by `,` inside the equivalence, or no separator if of size 1 atomic sequence).

So the engine's parser will descend into the tree in the following manner : 
- Split a sheaf chain in a serie of sheaves enclosed with `[...]` (ex : `foo[bar]baz` is split into `foo`, `bar`, `baz`). Each one is a sheaf.
- Split each sheaf content in fragments with `*` (ex: a sheaf `foo * bar * baz`is split into `foo`, `bar`, `baz`).
- Split each fragment in a serie of equivalences enclosed with `(...)` (ex : `foo(bar)baz` is split into `foo`, `bar`, `baz`). Each one is an equivalence.
- Split each equivalence content with `,` (ex: `foo,bar,baz`is split into `foo`, `bar`, `baz`).

As you can see, this is a tree structure with nodes of different nature depending of the depth of the node. Thus I'm not sure it's a good idea to try to highlight these concepts, due to the entanglement nature of all these concepts. IMHO you should probably limit yourself to : 

- variables
- delimiters : `[`, `]`, `(`, `)`, `,`, `*`, etc

And that's all for the left part, probably ?
For the right part you can safely add the tokens. But I'm not even sure that it's useful since all that is not a variable is a token.

Is it clearer or do you want me to develop more?

**Comment by laicasaane** [comment]
> all that is not a variable is a token

The current term I use for predefined things in the engine and charset is "symbol", e.g. {NULL}, {NBSP}, TINCO, PARMA,... (And the underscore symbol that marks the start and end - not the underscore that is an input character). Using One Dark Pro theme, symbols will be colorized in purple because they are marked as "keyword.symbol".

> And that's all for the left part

I would like to know if there should be any different between the left part of a rule (`-->`) and the left of the variable assignment (`===`/`<=>`)?

**Comment by BenTalagan** [comment]
> I would like to know if there should be any difference between the left part of a rule (-->) and the left of the variable assignment (===/<=>)? Also the right? In my view the left and right side of a rule are equivalence to the right and left of an assignment. Is it correct?

Yes and no. The left part of === and <=> is very restrictive : it can only be one and only be one variable (that means that for highlighting purpose what you've done would work anyway on a correct case).

On the right part of === and <=>, it can virtually be anything because a variable can be used on the left part of a rule or on the right side of a rule. So here, you're stuck because you cannot know. I'd suggest to colorize nothing (or use one and only one color), except maybe for delimiters. A variable definition is a substitution (that is done immediately with === or at usage time with <=>) so when declaring a variable, nothing really "logical" happens.

Maybe you should drop symbol highlighting for output tokens, and keep only what works on both side : variables, delimiters, pre-defined constants. Else you will not be able to have something perfect.

**Comment by laicasaane** [comment]
> Maybe you should drop symbol highlighting for output tokens, and keep only what works on both side : variables, delimiters, pre-defined constants. Else you will not be able to have something perfect.

That's right. Because of the limitation of TextMate grammar, we cannot know what is what exactly in this case of lazy rules. Well, I should keep myself away from perfectionism. Anyways, I would commit these changes later. Today I'm away from work ;)

**Comment by BenTalagan** [comment]
Ok, have a nice rest!

**Comment by laicasaane** [comment]
After having a big problem with comments in rule grammar, I decide to simplify the rule and variable assignment grammar. It won't recognize the left and right parts anymore, but just variables, delimiters and some predefined tokens.

**Comment by BenTalagan** [comment]
> Only the first block \** {UNI_EDD0} --> {A} **\ is recognized as a comment.

Not sure if what you were really trying to do but in your example : 

`\** {UNI_EDD0} --> {A} **\ --> {B} **\ --> {C} **\`

There's only one comment opening `\**`, and three comment closing `**\`, so the behaviour seems correct to me :) . 

Otherwise, if you were trying to put comments within comments, it's not possible (it's a common problem in C/C++ for example).

**Comment by laicasaane** [comment]
For me the normal behaviour should be: the start \** and the final **\ are recognized as the boundary of a comment block, all **\ that stand in between should be seen as normal characters inside this block.

**Comment by BenTalagan** [comment]
Nested comments are usually not supported in common languages (C/C++/Java, etc...). I don't support them in glaeml (and I really do not want to as I it can result in a parsing nightmare). The one thing I could add eventually is an inline comment syntax but honestly I'm not sure there's a need for it. You should just stay with your current behavior, it's perfect and matches the language spec :) !

**Comment by laicasaane** [comment]
So I will just let it be. I think the grammar is now completed, I dont know or see anywhere that needs to be improved unless you tell me.

**Comment by BenTalagan** [comment]
I've had a look at your work today. I had forgot how it can be difficult to have a clean syntax highlighting with these grammars, especially if you want to handle well comments anywhere.

In fact, even the most common grammars in textmate (js, xml, etc) do not handle well comments if they are placed at unusual positions : 

```js
function /* vicious comment */ myfunction() {
}
```
will not be highlighted correctly in TextMate.

We have the same problem here, and I could not find an easy way to do it. So this makes the grammar regexps pretty much unreadable. I really wonder if you shouldn't just drop comment handling in these positions since it makes it overly complicated. What do you think?

The rest of the grammar is pretty much detailed and has a pretty big coverage ; I would probably have stayed more generic (but it's cool). I will rework the generic grammar for glaeml and add it to your extension to illustrate my words.

**Comment by BenTalagan** [comment]
One other comment : macro and section are marked as section, not function (on the contrary of other tags like option, entry, etc). Is it intended? I feel like it's not homogeneous.

**Comment by laicasaane** [comment]
> Is it intended?

It's not. I just don't know what is the right term.

**Comment by BenTalagan** [comment]
> It's not. I just don't know what is the right term.

That was not my point : my question was, it's different from the other rules you've wrote : `options`, `changelog`, `entry`, etc, they all use `entity.name.function` but `macro` and `deploy` use `entity.name.section`. They are the only ones, and I don't see why. Is it a typo or is it there a reason for that?

**Comment by laicasaane** [comment]
Maybe I've just forgot what they should be and used the wrong term. Because I just wrote the grammar for macro and deploy when I realized there is macro in the Japanese mode.

**Comment by BenTalagan** [comment]
Ok! So I can just replace them by `function` without altering what you wanted to do ?

**Comment by laicasaane** [comment]
Yeah, I've fixed their naming now.

**Comment by BenTalagan** [comment]
Just a word to let you know I've merged your PR, and refactor a few things afterwards : 

- Added a generic grammar (very simple)
- Refactored glaem files type name to "Glaemscribe Mode"
- Refactored cst files type name to "Glaemscribe Charset"
- Added glaeml file type "GlaeML" (generic glaeml file, not necessarily related to glaemscribe).

**Pull request merged**
